endpoint: ""
status: "Ready to lift off!"

storageType: "MySQL"
mysql:
  "jdbcUrl": "jdbc:mysql://{host}:{port}/{database-name}"
  "host": "127.0.0.1"
  "port": "3306"
  "user": "rocketDiscordUser"
  "password": "foo-bar"
  "database-name": "RocketDiscord"
  "pool-size": 2

youtubeOauth2: "your-youtube-api-key"
initializeOauth2ForYoutube: false

adminIds:
  - "419203785190014987"